# Generated by Django 2.2.3 on 2019-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190716_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biodata',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
