# Generated by Django 2.2.3 on 2019-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teamusers_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamusers',
            name='team_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
